### ISSUE TITLE
How to print large height image?

### ISSUE THREAD

**Issue by phonsay** [MFori/Android-Bluetooth-Printer#1]
How to modify height and width of images to print?

**Comment by pabloko** [comment]
Very useful lib indeed, run into this topic, theres 2 blocks on decodeBitmap method that you can edit to achive more size

```
if (widthHexString.length() > 2) {
            //return null; //comment this return
        }
...
if (heightHexString.length() > 2) {
            //return null; //comment this return
        }
```
But be careful to not overflow your printer, this seems to be a basic overflow protection but leaving that way made a bit confusing to debug. Maybe it will make more sense to throw an exception.
