### ISSUE TITLE
is there tutorial use this library

### ISSUE THREAD

**Issue by kickymaulana** [MFori/Android-Bluetooth-Printer#2]
please help me .. is there tutorial in blog use this library?

**Comment by mfori** [comment]
Hi, there is no tutorial yet. Just copy BluetoothPrinter.java file to your project and follow the example in readme.

**Comment by kickymaulana** [comment]
how to get bluetooth device at this code

BluetoothDevice mBtDevice = btAdapter.getBondedDevices().iterator().next();

**Comment by mfori** [comment]
Take look at: https://developer.android.com/reference/android/bluetooth/BluetoothAdapter.html#getBondedDevices()

**Comment by kickymaulana** [comment]
ok it works. thanks. but when I have a problem. please help me
