### ISSUE TITLE
how to print text with align left and right 

### ISSUE THREAD

**Issue by kickymaulana** [MFori/Android-Bluetooth-Printer#3]
how to print text with align left and right in one line like this

Harga             : 10.000
total               : 20 000

**Comment by mfori** [comment]
You can use constants ALIGN_CENTER, ALIGN_RIGHT, ALIGN_LEFT for setAlign(int) method.
Combination of more types of aligments in one line is not supported. But you can calculate it for witdh of line and fill with spaces.
