### ISSUE TITLE
How to align image to center? i tried using setAlign but it only aligns text

### ISSUE THREAD

**Issue by TalissonJunior** [MFori/Android-Bluetooth-Printer#4]

**Comment by mfori** [comment]
Bitmap alignment could work, be sure that bitmap is not wider than your canvas (including empty borders)

**Comment by TalissonJunior** [comment]
> Bitmap alignment could work, be sure that bitmap is not wider than your canvas (including empty borders)

You have any examples or links on how to do that? and my bitmap is 120 height and width, so it is not wider than my canvas

**Comment by TalissonJunior** [comment]
I found a solution, thank you
